import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  M_PLUS_Rounded_1c,
  Noto_Sans_JP,
} from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/context/LanguageContext";

const mPlusRounded1c = M_PLUS_Rounded_1c({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-m-plus-rounded-1c",
});

const notoSansJP = Noto_Sans_JP({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-Noto-Sans-JP",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kota's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mPlusRounded1c.variable} ${notoSansJP.variable} antialiased`}
      >
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
